### ISSUE TITLE
Failing to cache on Windows

### ISSUE THREAD

**Issue by psychobolt** [rharkor/caching-for-turbo#37]
Hi, there is a error with finding the temporary cached data on Windows. See logs:

```sh
Error: Unable to upload cache: Error: ENOENT: no such file or directory, open 'D:\tmp\cache-24932.tg.bin'
{"level":50,"time":1719255262077,"pid":3380,"hostname":"fv-az1489-381","reqId":"req-a","req":{"method":"PUT","url":"/v8/artifacts/1d9d215f8c05f1f4?slug=turbogha","hostname":"localhost:41230","remoteAddress":"::1","remotePort":50049},"res":{"statusCode":500},"err":{"type":"Error","message":"ENOENT: no such file or directory, open 'D:\\tmp\\cache-24932.tg.bin'","stack":"Error: ENOENT: no such file or directory, open 'D:\\tmp\\cache-24932.tg.bin'","errno":-[40](https://github.com/psychobolt/vite-storybook-boilerplate/actions/runs/9652918639/job/26624145421#step:10:40)58,"code":"ENOENT","syscall":"open","path":"D:\\tmp\\cache-24932.tg.bin"},"msg":"ENOENT: no such file or directory, open 'D:\\tmp\\cache-24932.tg.bin'"}
```

**Comment by rharkor** [comment]
Hi 👋,

Can you share me the full output logs of the job and post job please, also if you can show me the action file in order to reproduce it.

What I suppose is that my package doesn't recognize being used in a GitHub action and tries to start in dev mode. This may be due to some missing environment variables (maybe if run from a custom worker).

**Comment by psychobolt** [comment]
You can see the full log link in my comment

```sh
....https://github.com/psychobolt/vite-storybook-boilerplate/actions/runs/9652918639/job/26624145421#step:10:40
```

Also the issue can be narrowed down to using linux paths as noted [here](https://github.com/search?q=repo%3Arharkor%2Fcaching-for-turbo%20.bin&type=code). Would be preferred to use `runner.temp` ?

**Comment by rharkor** [comment]
Thanks for your feedback, in fact I was using the runner.temp folder for the logfile server but I forgot to use it for temporary cached files.

I fixed it in the latest version (https://github.com/rharkor/caching-for-turbo/releases/tag/v1.4).

Thanks for your patience

**Comment by psychobolt** [comment]
Thank you for the very fast updates!

**Comment by psychobolt** [comment]
@rharkor 

I am still getting the same error. See action log: https://github.com/psychobolt/vite-storybook-boilerplate/actions/runs/9667642568/job/26669944781#step:10:39

**Comment by rharkor** [comment]
Oh yes stupid me releasing without packaging the app :face_in_clouds:

**Comment by rharkor** [comment]
Okay finally, I added some tests in my CI to make sure that it wont appear again.

Check v1.5 and let me know if it works for you :wink:

**Comment by psychobolt** [comment]
Thanks! It is working for me now
